---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: site/content
  label: Pages
  create: all
- path: site/content/speaker
  label: Speaker
  create: all
- path: site/content/sponsor
  label: Sponsor
  create: all
- path: site/content/exhibitor
  label: Exhibitor
  create: all
upload_dir: site/static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.43'
